"""empty message

Revision ID: 6a1d3a8c45d7
Revises: 756676944db5
Create Date: 2018-12-19 17:23:14.567845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1d3a8c45d7'
down_revision = '756676944db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_house', sa.Column('order_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_house', 'order_count')
    # ### end Alembic commands ###
