"""empty message

Revision ID: 756676944db5
Revises: 5faf1efd4bb5
Create Date: 2018-12-18 17:00:21.419260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756676944db5'
down_revision = '5faf1efd4bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_house', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ihome_house', 'ihome_area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ihome_house', type_='foreignkey')
    op.drop_column('ihome_house', 'area_id')
    # ### end Alembic commands ###
